### PR TITLE
Resolves issue #7 (and adds one feature)

### PR DESCRIPTION
**Pull request by djreisch**
Changed the program icon to an icon I had used for a (now) deprecated Steam application. This icon shows well on most colored taskbars.

Added: Added package Costura.Fody which allows for dll/resource bundling. This will make releases more simple, being only an exe would have to be downloaded.

In addition, the compiled and digitally signed executable (signed by me) is attached (in zip format).

NOTE: I did not increment the application/product version. I wasn't sure how far/if at all it should be advanced
[SteamBulkActivator.zip](https://github.com/Ezzpify/SteamBulkActivator/files/1319242/SteamBulkActivator.zip)

EDIT: Changed wording for readability

### CODE REVIEW

**Comment by Ezzpify** [comment]
I will look when I get home but I will not release anything that is not compiled by me - sorry.

**Comment by djreisch** [comment]
Understandable. The merge doesn't include any settings for the compile, just the changes regarding the icon.

I really want to get this a little more visibility since it's such a useful program. The reason I suggested my compiled release is because I have a code signing certificate which doesn't send up any flags when running on windows. I have my compiled signed release on SteamBulkActivator.com even though it points to this GitHub page

**Comment by Ezzpify** [comment]
I will look at the new icon tomorrow as I also have a small redesign in mind.

To be honest I'm not sure how I feel about you releasing your own binaries on your website since you made it look like it's the official site.

**Comment by djreisch** [comment]
I will respectfully take it down. It originally was pointed to my personal repository because I had maintained it quite a bit. Now that you are starting to merge branches it points back at your github. I have my binary on there because it's signed and verified so it doesn't throw as many flags up. If you'd like to discuss this further and keep it a little more private you can contact me at daniel@reischnet.com

**Comment by Ezzpify** [comment]
Merged regex manually.

Thanks.

**Pull request closed without merging**
